// Code generated by "stringer -type=ErrCode"; DO NOT EDIT.

package errors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AssertionError-0]
	_ = x[ParseError-1]
	_ = x[ServerNotAvailable-2]
	_ = x[NetworkError-3]
	_ = x[ConnectionResetError-4]
	_ = x[AdbError-5]
	_ = x[DeviceNotFound-6]
	_ = x[FileNoExistError-7]
}

const _ErrCode_name = "AssertionErrorParseErrorServerNotAvailableNetworkErrorConnectionResetErrorAdbErrorDeviceNotFoundFileNoExistError"

var _ErrCode_index = [...]uint8{0, 14, 24, 42, 54, 74, 82, 96, 112}

func (i ErrCode) String() string {
	if i >= ErrCode(len(_ErrCode_index)-1) {
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrCode_name[_ErrCode_index[i]:_ErrCode_index[i+1]]
}
